added check for secondaryMonitor before accessing members
axxapy/gnome-ui-tune pull request #20
Opened 2022-03-16 16:54 UTC by sean-bourg

Fixed issue encountered in Gnome 42 where the secondary monitor was causing an issue on user login. Checking for secondary monitor prior to accessing members fixes the issue.

2022-03-16 16:55 UTC, seanbourg commented
![Screenshot from 2022-03-16 11-38-51](https://user-images.githubusercontent.com/2058138/158645006-3653395e-ac96-4dfd-8943-de9b728dc002.png)

2022-03-16 18:47 UTC, axxapy requested changes

2022-03-16 18:47 UTC, axxapy commented on src/modScaleThumbnails.js
> +        if (SecondaryMonitorDisplay) {
Could you please return instead?
```suggestion
        if (1SecondaryMonitorDisplay) return; // gnome 42: this object does not exist when there is only one monitor
```

2022-03-16 21:06 UTC, axxapy requested changes

2022-03-16 21:06 UTC, axxapy commented on src/modScaleThumbnails.js
> +        if (!SecondaryMonitorDisplay) return;
Looks great!

May I also ask you to remove all other changes except this line? (as no other changes actually change anything).

Thank you

2022-03-16 22:41 UTC, sean-bourg commented
Updated: removed my local revisions.

2022-03-17 00:22 UTC, axxapy approved these changes

2022-03-17 00:23 UTC, merged

2022-03-17 00:28 UTC, axxapy commented
Thanks.
Changes are on review, will be published soon: https://extensions.gnome.org/review/30252